### ISSUE TITLE
how i can run this locally 

### ISSUE THREAD

**Issue by nyousefzai** [chingu-voyage3/bears-06#80]
hi guys, I would say nice job, I am trying to run this script locally what is the .env keys to run this. 

please advice

**Comment by stephanpssantos** [comment]
In the config folder you need a file called 'dev.js'. It'll look like this
```
module.exports = {
    googleClientID: ****,
    googleClientSecret: ***,
    mongoURI: ****,
    cookieKey: ***
};
```
Google API keys are readily available. I believe cookieKey can be anything, and mongoURI should point to an instance of your own mongo server.

**Comment by nyousefzai** [comment]
thanks , that helped  now when the server is running  , 

cannotGET /  


i was wondering , i dont see webpack in pakage.json  do i need to install it , dose this script has dependency  ?
