### ISSUE TITLE
how to to start the script? 

### ISSUE THREAD

**Issue by nyousefzai** [chingu-voyage3/bears-06#81]
now i have the dev.js and has be configured . 
i do npm start   server is start to run but  nothing is happening .

i also did  npm run server , and npm run client 

please advice . Thanks
<img width="1151" alt="screen shot 2018-02-14 at 1 18 49 pm" src="https://user-images.githubusercontent.com/27225894/36228672-b0b9165a-1189-11e8-9964-4e06671d06da.png">

**Comment by nyousefzai** [comment]
a little start doc would be nice

**Comment by vannya** [comment]
I'll get the start documentation up within a day or so.  Thanks for the reminder!

**Comment by nyousefzai** [comment]
Thanks,  i did create the dev.js file with config now the server is running but i can get anything from client side? i am really excited to see how this run on my machine

**Comment by nyousefzai** [comment]
i  figured out

**Comment by heyAyushh** [comment]
Hi @nyousefzai does your login work after creating dev.js
