### ISSUE TITLE
render homelocation.address

### ISSUE THREAD

**Issue by nyousefzai** [chingu-voyage3/bears-06#85]
On = client/src/common

listing.js

i am trying to render homelocation.address

      </div>
        {overview.homelocation.address}
      </div>
on line 286
thanks for your help in advance.

**Comment by vannya** [comment]
Homelocation isn't being passed in as a prop to Listing.js.  You will need to add that change by passing in the data if you choose to change that.

**Comment by nyousefzai** [comment]
thanks

**Comment by nyousefzai** [comment]
HEY VANNYA ,   sorry to bother you again , can give me a small example how to do this , i have been trying to do this an i run to some issues .

**Comment by stephanpssantos** [comment]
What does it say when you try to do `{overview.homelocation.address} `? It seems like it should have that data

**Comment by nyousefzai** [comment]
this is what i get what that try
<img width="1403" alt="screen shot 2018-03-02 at 3 24 11 pm" src="https://user-images.githubusercontent.com/27225894/36926687-e9907e36-1e2d-11e8-81be-1a99c049b7df.png">

**Comment by stephanpssantos** [comment]
You're getting that because the default data object (emptyData in searchgallery.js) doesn't have a homelocation field. You can either add a homelocation field there or change your call to ```
<div className="listing__text--title">
              {(overview.homelocation && overview.homelocation.address)}
            </div>
```

**Comment by nyousefzai** [comment]
That totally worked Thanksssss
