### ISSUE TITLE
http://localhost:5000/api/homes

### ISSUE THREAD

**Issue by nyousefzai** [chingu-voyage3/bears-06#86]
i can get data from outside call, like postman .

No Security ???

**Comment by nyousefzai** [comment]
https://bearbnb-06.herokuapp.com/api/homes
<img width="1655" alt="screen shot 2018-03-03 at 4 59 43 pm" src="https://user-images.githubusercontent.com/27225894/36940949-96ec19d8-1f04-11e8-82c2-5387841b26b5.png">

**Comment by nyousefzai** [comment]
i can get   https://bearbnb-06.herokuapp.com/api/users 
as well

**Comment by nyousefzai** [comment]
the issue here is that only client should be able to consume the data not anybody. 

all you have to to do is a get request and there is the data , i will start working on solution  let me know what you guys think , or if there is another way to secure this .

**Comment by stephanpssantos** [comment]
We don't consider this an issue, but please feel free to post your solution if you ever resolve your issue
